---
title: ""
format: 
  docx: 
    reference-doc: landscape-template.docx
---


## sumary of events in table (no Description field)



| Report_ID | Report date | Classification | Device    | P('pain'\|doc) | Event     | Event type                 | Source              |
|--------:|:--------|:--------|:--------|--------:|:--------|:--------|:--------|
|     30531 | 2013-05-17  | pelvic_mesh    | Class IIb |          0.036 | Injury    | Implantable Device Failure | Industry            |
|     37537 | 2015-02-06  | other_device   | Class IIa |          0.029 | Injury    | Mechanical                 | Industry            |
|     36797 | 2015-08-27  | other_mesh     | Class III |          0.020 | Injury    | Material                   | Industry            |
|     40917 | 2016-04-24  | pelvic_mesh    | Class IIb |          0.538 | Injury    | Other                      | Consumer            |
|     43792 | 2016-11-23  | pelvic_mesh    | Class IIb |          0.000 | Injury    | Implantable Device Failure | Health Professional |
|     45432 | 2017-03-29  | hernia_mesh    | Class IIb |          0.214 | Injury    | Other                      | Consumer            |
|     44402 | 2017-12-01  | other_device   | Class III |          0.000 | No Injury | Other                      | Other               |
|     45624 | 2017-12-04  | other_device   | Class 1   |          0.000 | No Injury | Mechanical                 | Health Professional |
|     45265 | 2017-12-18  | other_device   | Class IIb |          0.250 | Injury    | Other                      | Industry            |



## Table 1 with full `Description` field





| Report_ID|Report date |Classification |Device    | P('pain'&#124;doc)| ARTG no.|Event     |Event type                 |Source              |Description               |
|---------:|:-----------|:--------------|:---------|------------------:|--------:|:---------|:--------------------------|:-------------------|:---------------------------------------------------------|
|     30531|2013-05-17  |pelvic_mesh    |Class IIb |              0.036|   150342|Injury    |Implantable Device Failure |Industry            |It was reported that the patient was implanted with a Pinnacle Anterior/Apical Pelvic Floor Repair Kit. During a follow-up appointment 6 weeks post-procedure, the physician noted that the patient had apparently rejected the mesh, as there was some slight vaginal bleeding and none of the mesh seemed to adhere to the vaginal tissue.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           |
|     37537|2015-02-06  |other_device   |Class IIa |              0.029|   137859|Injury    |Mechanical                 |Industry            |Patient admitted for routine SFA angioplasty. The physician had completed the procedure without incident and had withdrawn the balloon catheter from the sheath. Whilst attempting to remove the sheath from the patient's groin in order to close the puncture site, the physician felt a lot of resistance. As the physician tried to pull and remove the sheath, the sheath broke off and some of the sheath was left inside the patient.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           |
|     36797|2015-08-27  |other_mesh     |Class III |              0.020|   219240|Injury    |Material                   |Industry            |3 weeks post-op, patient contacted the surgeon saying that the wound was opening, and she could see the implant. The patient sent photos, and there was a small wound dehiscence on one breast, with implant exposed. 2 days later the surgeon noticed the same process starting in the other breast. Within a couple of days, the dehiscence worsened, and he asked the patient be admitted to hospital for dressings and IV antibiotics. Patient underwent operation to have implants removed. During the operation he found the Veritas bilaterally ripped in half, thus exposing the implant, which then eroded the underside of the wound leading to an infection.                                                                                                                                                                                                                                                                                                                                                                                                |
|     40917|2016-04-24  |pelvic_mesh    |Class IIb |              0.538|    92718|Injury    |Other                      |Consumer            |Have had pelvic pain, pain with sex incontinence with bowel and bladder, cannot sit, walk, stand on feet for extended time.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            |
|     43792|2016-11-23  |pelvic_mesh    |Class IIb |              0.000|   117686|Injury    |Implantable Device Failure |Health Professional |Vaginal mesh erosion causing bleeding.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 |
|     45432|2017-03-29  |hernia_mesh    |Class IIb |              0.214|    98833|Injury    |Other                      |Consumer            |Atrium mesh implanted in my abdomen. Severe right sided abdominal pain ongoing. Also had further surgery to repair hernia due to reoccurrence of hernia.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               |
|     44402|2017-12-01  |other_device   |Class III |              0.000|   149128|No Injury |Other                      |Other               |Sponsor distributed a Customer Letter dated 20th December 2016 announcing the immediate discontinuation of their CE-marked Umbilical Vessel Catheter products. They indicated no replacement for the items. This is considered insufficient notice to adequately source alternative products and meet clinical demand. Sponsor is currently withholding stock and rationalizing it across Australia.  An alternative similar product has been sourced, however this product is not in supply in Australia and is on backorder. The product range of the alternative supplier does not cover the product range supplied by the sponsor in use.  A limited stock is in place at the facility (a tertiary care hospital for the delivery and treatment of pre-term neonates) of the Single Lumen 3.5Fr catheters, which are used regularly. The clinical impact of not having a supply of this size is considered significant.  Other products in the range no longer available by the sponsor are also in demand at this facility, however a greater stock is available. |
|     45624|2017-12-04  |other_device   |Class 1   |              0.000|   121950|No Injury |Mechanical                 |Health Professional |Operating table started tilting patient on its own during procedure. Emergency stop button pressed - table stopped briefly and began to tilt patient further again.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    |
|     45265|2017-12-18  |other_device   |Class IIb |              0.250|   177101|Injury    |Other                      |Industry            |Pain, possible rupture and swelling around prosthesis.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 |













